project:
  type: book
  output-dir: docs
  render: 
  - "*.qmd"      # Only render QMD files
  - "!slides/"   # EXPLICITLY IGNORE this folder for rendering
  resources: 
  - slides/
  - images/
  - correction/

book:
  title: "CASA0023 Remotely Sensing Cities and Environments Learning Diary"
  author: "Christy Choi"
  date: "2/1/2026"
  navbar:
    logo: images/casa_logo.jpg
    collapse: true
    collapse-below: lg
    background: light
    search: true
    reader-mode: true
    right:
      - icon: github
        href: "https://github.com/christychoicc"

  chapters:
    - index.qmd
    - intro.qmd
    - sensor.qmd
    - correction.qmd
    - references.qmd


bibliography: references.bib

format:
  html:
    theme:
      #- cosmo
      #- brand
      light: [cosmo, flatly]
      dark: [cosmo, darkly]
    code-link: true

editor: visual

