# Welcome ! {.unnumbered}

Hello and welcome to my page on Remote Sensing. This page is an online learning diary for CASA0023 Remotely Sensing Cities and Environments 25/26. This learning diary records my week-by-week progress, reflections, and applications as I engage with new concepts, methods, and case studies in remote sensing. Through application sections each week, I want to step out of my comfort zone and explore unfamiliar cities and environments to broaden my geographic perspective.

## About me

I am a current master’s student at the Bartlett Centre for Advanced Spatial Analysis (CASA), University College London (UCL) studying MSc, Urban Spatial Science. I hold a bachelor’s degree in BSc, Planning and Real Estate from the University of Manchester during 2022-2025. Through my previous studies, I became increasingly interested in how data and technology can be used to better understand urban systems, supporting planning decisions, and respond to environmental challenges

I am particularly interested in how remote sensing can be used to understand patterns and changes in cities and landscapes that may not be directly interpretable from ground. From a planning background, I see this module as a very good opportunity to expand my technical skills and to develop a stronger understanding of how satellite imagery, geospatial analysis, and environmental data can be applied in real-world contexts.

## In this Learning Diary

Each chapter will be covering contents taught in the corresponding week:

1.  Introduction
    -   Getting started with remote sensing, this introduction will go through types of sensors, spatial resolutions and practical data pre-processing with Lisbon as the study area.
2.  Sensor
    -   Looking at Sentinel-1, the slides will provide a summary of the sensor, its mission, technical specifications, key objectives and applications, benefits and limitations, and reflections
3.  Correction
    -   Explores preprocessing corrections and enhancements with Hong Kong as a study area, include mosaicking of Landsat 8-9 tiles, NDVI, GLCM texture, and PCA analyses.
4.  Policy
    -   Looking at OneNYC 2050
5.  Google Earth Engine
6.  Classification I
7.  Classification II
8.  Temperature
